[package]
authors = [
    "The Cortex-M Team <cortex-m@teams.rust-embedded.org>",
    "Jonathan Pallant <github@thejpster.org.uk>",
    "Jorge Aparicio <jorge@japaric.io>",
]

description = "A heap allocator for Cortex-M processors"
repository = "https://github.com/rust-embedded/alloc-cortex-m"
documentation = "https://docs.rs/alloc-cortex-m"
readme = "README.md"
edition = "2018"

keywords = [
    "allocator",
    "arm",
    "cortex-m",
]
license = "MIT OR Apache-2.0"
name = "alloc-cortex-m"
version = "0.3.5"

[dependencies]
cortex-m = "0.6.2"

[dependencies.linked_list_allocator]
default-features = false
version = "0.8.1"

[dev-dependencies]
cortex-m-rt = "0.6.12"
